### ISSUE TITLE
Test compatibility with Firefox

### ISSUE THREAD

**Issue by AlessandroFC15** [AlessandroFC15/Fuck-Youtube#32]

**Comment by IkeKap** [comment]
Iirc the new webextensions API in Firefox quantum is made to make it really easy for devs to port chrome apps to Firefox. Also this extension (https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/) might allow users to just simply install the app from the chrome web store

**Comment by AlessandroFC15** [comment]
@IkeKap I've been looking into it, it should be pretty simple to port it to Firefox indeed. According to the extension compatibility test for Firefox (https://www.extensiontest.com/), the extension is compatible with Firefox. Some warnings appeared but it should be easy to fix. 

Thanks for pointing out the extension to install it from the Chrome Web Store. I was not aware that even existed :)

**Comment by AlessandroFC15** [comment]
Extension is published in the Firefox Add-Ons Store.

I've chosen to publish in an experimental phase first, just to see how the extension behaves in a different browser.

You can find it right here: https://addons.mozilla.org/pt-BR/firefox/addon/f-ck-youtube/

Any feedback and errors found would be greatly appreciated.

**Comment by IkeKap** [comment]
just in case people want to view the english version, here's the [link](https://addons.mozilla.org/en-US/firefox/addon/f-ck-youtube/)

For people viewing this conversation, 9 times out of 10 you can usually change the language of a site by changing the country code of the site (ex. en-US, or pt-BR)

**Comment by tyteen4a03** [comment]
Tried this on https://www.youtube.com/watch?v=Bb3wUNv32ys, now the player disappears completely, even after uninstalling the extension.

**Comment by AlessandroFC15** [comment]
@tyteen4a03 Thanks for the feedback. I am have a pretty good idea of what's happening on this bug. If the player is still missing, can you try to hold down the Shift key and left-click the Reload button and see if the issue stills persists?

Again, thanks for the feedback :)

**Comment by AlessandroFC15** [comment]
I've set to status of the extension to invisible while I work on some issues. Should be available again soon.

**Comment by tyteen4a03** [comment]
That did not work.

**Comment by AlessandroFC15** [comment]
@tyteen4a03 Just to make sure, are you having this problem in Firefox or Chrome?

**Comment by tyteen4a03** [comment]
Firefox.

**Comment by AlessandroFC15** [comment]
@tyteen4a03 I would advise that it's best if you uninstall the version for Firefox for now. I'm still working on some issues and I'll let you know when I release a version for Firefox that I consider to be reliable.

Thanks :)

**Comment by Tronslate** [comment]
We can try to use this portal https://www.vpnroot.com/

**Comment by AlessandroFC15** [comment]
The process of porting the extension to Firefox has started on branch [firefox](https://github.com/AlessandroFC15/Fuck-Youtube/tree/firefox). 

Early next year we should have a version for tests released :)

**Comment by AlessandroFC15** [comment]
Version for tests on Firefox is live.

You can check it out right here: https://addons.mozilla.org/en-US/firefox/addon/f-ck-youtube/

**Comment by AlessandroFC15** [comment]
Firefox version has been tested and is now ready for use. The link remains the same: https://addons.mozilla.org/en-US/firefox/addon/f-ck-youtube/
