### ISSUE TITLE
Doesn't work on some country

### ISSUE THREAD

**Issue by unixfox** [AlessandroFC15/Fuck-Youtube#33]
I'm Belgian and I tried to watch [a video](https://www.youtube.com/watch?v=DW9jNJBi14w) restricted for French viewers but the extension didn't find any proxy to bypass the restriction for the France.

So I found an app that proxy YouTube and I hosted it on a French server: https://github.com/dmhacker/dmhacker-youtube
Maybe we could discuss integrating servers like this into your extension?
And unfortunately this app doesn't give any choice to choose the quality of the video.

The URL of my proxy is https://fr.ytproxy.unixfox.eu and here is the URL of the creator of the app: https://dmhacker-youtube.herokuapp.com/ (hosted in US I think).

I think this issue will be the case for others countries other than France.
I can deploy others proxy in UK and Austria if you want to.

**EDIT**: I found another proxy app: https://github.com/licson0729/node-YouTubeStreamer and there is lot's of others here: https://github.com/search?o=desc&p=1&q=youtube+proxy&s=stars&type=Repositories&utf8=%E2%9C%93

**Comment by AlessandroFC15** [comment]
@unixfox Hi, Emilien.

Thanks for opening this issue. Of course we can discuss integrating this into the extension. Do you allow me to use your proxy as another source to find mirrors? I'd be happy to handle the integration part without any problem.

It would be fantastic to have other proxy in UK and Austria as well. If you can provide that, we'd be very grateful. 

About the choices of quality of video, this is a known issue (see #11) and we'll be working on it in the near future.

As there is a lot of proxy apps, I think the best way to handle this would be to gradually add the ones that we feel are the best suited for our project. 

Thanks for showing interest in helping the project grow. You support is greatly appreciated.

**Comment by unixfox** [comment]
Thank you for your reply!

If you don't mind I'll take the time this weekend to setup a bunch of others Youtube proxies properly with a separate domain, using cloudflare to hide the origin IP of the server and so on.
I'm doing all of this because I want to have the least possible link to me in case YouTube do lawsuits.

I let my instance online for testing and if you can don't push it to the production extension.

**Comment by AlessandroFC15** [comment]
Thank you for your help.

Take as much time as you feel is needed to setup everything. Your support is very much appreciated on this project and I totally understand your concerns regarding lawsuits and everything. Again, feel free to take as much time as you want to do everything in your own terms. Whenever you feel you are getting close to finishing it, just let me know so I can start the integration part, ok? :)

Your instance online has just been pushed to production for a quick test in a real environment but if you want I can take it out at anytime. Just say the word and I'll pull it back.

I know this sounds repetitive, but thanks again for your help :)

**Comment by unixfox** [comment]
You are welcome! I appreciate puting my free time into great projects.
I prefer if you remove my testing instance on the production extension.

I'll come back to you as soon as I've tested every software and deploying properly some proxies. I've a bunch of ideas to cover a lot's of countries to bypass the YouTube restriction.

PS: I'm a Firefox user and I'm very looking forward to this issue #32 :).

**Comment by AlessandroFC15** [comment]
Thanks for being so willing to help. Unfortunately Google has removed the extension from the Chrome Web Store just now. 

So I just wanted to tell you to not spend your time developing it unless I find a way to talk to them about this and maybe get it republished. 

They said the extension did not comply with their policies. I'll see what I can do about it :(

Thanks!

**Comment by unixfox** [comment]
I knew it, someone reported the extension.
I don't think Google will allow this extension, this goes against their rules.

You've got two options for Google Chrome users:
- Publishing this extension on a separate website.
- Redevelop the whole extension into an userscript for making compatible with Tampermonkey/Greasemonkey, this way Google can't circumvent your _extension_, this makes very easy to install and auto update.

**Comment by AlessandroFC15** [comment]
I also don't think Google will allow it. Thanks for providing input on the options to move forward :)

I've managed to get the extension working already on Firefox, so, I should be publishing tomorrow. At least that way people can continue to install the extension in another browser.

About the options for Chrome, I'm thinking about developing both. What are your thoughts on it?

**Comment by unixfox** [comment]
I'm happy to see that you got the extension working on Firefox, if you need a tester I'm here.

About the options for Chrome: I would say that maintening two types of extensions (extension and userscript) can be hard but it's up to you if you've enough free time to spend on these two options.
I also tell you about the first option that by installing manualy an extension the user can't have auto updates from the developper so he will have to manualy update the extension each time there is a new version. This issue will not be the case for the userscript if the user uses Tampermonkey/Greasemonkey because these extensions supports natively auto updating the userscript.

**Comment by AlessandroFC15** [comment]
You know what, you're absolutely right. I had not considered the problem that the extension doesn't autoupdate on a manual install. And I feel like that's a pretty big deal. 

So I think it's pretty clear then that we will be moving forward with the Tampermonkey/Greasemonkey solution coupled with the Firefox release. I feel this way we can still offer the product to those who are interested in a relatively easy way reaching a decent amount of people. It's not like the Chrome Web Store but we will improvise, adapt and overcome this. Thanks for being so supportive in this tough situation.

**Comment by unixfox** [comment]
I'm not saying that you have to drop support for the Chrome extension if you want to continue working on the extension for Firefox but take note of this issue, what I mean is that if the code base is similar to Firefox web extensions you could only release big updates for Chrome users as long as you don't have to provide a huge amount of work to readjust the Firefox extension to Chrome and you just have to send a notification to the users to ask them if they want to update the extension when there is a new version out.
By doing this way you can also publish the extension for Firefox on the same separate website in case the extension is taken down by Mozilla. So if the extension is taken down just send a notification to Firefox users that if they still want to have updates for this extension they will have to visit the website.
Moreover, by supporting the Chrome extension, you can also publish the extension on the extension store of [Opera](https://addons.opera.com) and others Chrom~~e~~ _ium_ fork.

PS: Do you want to discuss on Gitter instead of being off topic (of the original issue): https://gitter.im? Just create a room linked to the repo and invite me.

**Comment by AlessandroFC15** [comment]
@unixfox I've created the room on Gitter and already invited you :)

**Comment by AlessandroFC15** [comment]
The video that caused the opening of this issue is now unblocked successfully with the new version of the extension available for Firefox, so, I think it makes sense to close this issue :)
