### ISSUE TITLE
extention doesnt work on this link 

### ISSUE THREAD

**Issue by gdc88** [AlessandroFC15/Fuck-Youtube#39]
Hi, the extention doesnt work on this link from israel:

https://www.youtube.com/watch?v=rS00xWnqwvI

![github](https://user-images.githubusercontent.com/34210225/33525356-7f5fe5d4-d836-11e7-9e5b-e0ae7ebf1d25.JPG)

thank you!

**Comment by AlessandroFC15** [comment]
Hello, @gdc88.

Thanks for the feedback. This video is also blocked in my country but everything worked as expected when I tried to use the extension. 

![captura de tela de 2017-12-03 14-39-46](https://user-images.githubusercontent.com/8843452/33527947-f4081d60-d837-11e7-9bcd-4749ab0f7166.png)

What version of the extension are you currently using? 

Do you get any kind of error when you try to access this website right here?
- www.genyoutube.net

Let me know so I can try to help you :)

**Comment by gdc88** [comment]
thanks for the reply,

no problems with www.genyoutube.net

extension is version 0.0.4

what i'd noticed is that after i **sign out** youtube - the extention worked

**Comment by AlessandroFC15** [comment]
Well, that's odd. A couple of bugs were fixed in new release (0.0.0.5). I'm not sure what might be causing this but if you can update your extension to the latest version, that would be good. 

You can find the .crx file right here: 
- https://github.com/AlessandroFC15/Fuck-Youtube/blob/master/releases/0.0.0.5/release_0.0.0.5.crx

If you are not sure on how to install the extension manually, follow the steps below:
- Uninstall the current version you have.
- Download the .crx file mentioned above.
- Open the extensions page of Chrome (enter chrome://extensions as the url)
- Drag and drop the downloaded file into the extensions page.
- That's it!

If the issue still persists, please let me know :)

**Comment by gdc88** [comment]
works! just a meter of version update:)

![works](https://user-images.githubusercontent.com/34210225/33528697-4f380b34-d86d-11e7-9678-a225d18307b8.JPG)


thank you!

**Comment by gdc88** [comment]
but the extension blocked by chrome after restarting chrome:

![chrome blocks](https://user-images.githubusercontent.com/34210225/33528861-c759c974-d870-11e7-8c17-408521a384df.JPG)

**Comment by AlessandroFC15** [comment]
Oh, ok.

On the extension page, do you have the option "Developer Mode" selected or not?

**Comment by gdc88** [comment]
tried already - same

**Comment by AlessandroFC15** [comment]
Ok, let's try another way then:

1. Uninstall the current version you have.
2. Download the .zip file right here (https://github.com/AlessandroFC15/Fuck-Youtube/blob/master/releases/0.0.0.5/release_0.0.0.5.zip)
3. Unzip the file
4. Open the extensions page
5. Make sure developer mode is checked
6. Click on "Load unpacked extension"
7. Select the folder that you unziped on step 3

Let me know how that goes :)

**Comment by gdc88** [comment]
same

**Comment by AlessandroFC15** [comment]
@gdc88 Ok, after some research and some tests, if you are using Windows, this video right here solved the issue for me: https://www.youtube.com/watch?v=p_me8EsADcU

The link to the file can be downloaded from the description and when Chrome blocks it saying it's dangerous and everything, just go to the downloads page (Ctrl + J) and allow the file to be saved. Run it as a admin and you should be good to go.

If that also doesn't work, there's really nothing much more that I can do to help you :(

But keep us posted if this works or not :)

**Comment by gdc88** [comment]
thanks - worked :)

**Comment by AlessandroFC15** [comment]
Great then, you're welcome!
